[2023-07-21 23:56:20,481] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_digitalskola_finalproject.insert_data_to_dim_case manual__2023-07-21T23:55:54.718845+00:00 [queued]>
[2023-07-21 23:56:20,528] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_digitalskola_finalproject.insert_data_to_dim_case manual__2023-07-21T23:55:54.718845+00:00 [queued]>
[2023-07-21 23:56:20,531] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-07-21 23:56:20,543] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-07-21 23:56:20,548] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-07-21 23:56:20,618] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): insert_data_to_dim_case> on 2023-07-21 23:55:54.718845+00:00
[2023-07-21 23:56:20,642] {standard_task_runner.py:52} INFO - Started process 5703 to run task
[2023-07-21 23:56:20,665] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_digitalskola_finalproject', 'insert_data_to_dim_case', 'manual__2023-07-21T23:55:54.718845+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/dag_digitalskola_finalproject.py', '--cfg-path', '/tmp/tmp5u7zn4qr', '--error-file', '/tmp/tmp8h859rla']
[2023-07-21 23:56:20,672] {standard_task_runner.py:80} INFO - Job 113: Subtask insert_data_to_dim_case
[2023-07-21 23:56:21,632] {task_command.py:369} INFO - Running <TaskInstance: dag_digitalskola_finalproject.insert_data_to_dim_case manual__2023-07-21T23:55:54.718845+00:00 [running]> on host 34be34978432
[2023-07-21 23:56:23,261] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_digitalskola_finalproject
AIRFLOW_CTX_TASK_ID=insert_data_to_dim_case
AIRFLOW_CTX_EXECUTION_DATE=2023-07-21T23:55:54.718845+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-21T23:55:54.718845+00:00
[2023-07-21 23:56:25,824] {transformer.py:100} INFO - DATA INSERTED SUCCESS TO TABLE dim_case
[2023-07-21 23:56:26,052] {python.py:173} INFO - Done. Returned value was: None
[2023-07-21 23:56:27,865] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_digitalskola_finalproject, task_id=insert_data_to_dim_case, execution_date=20230721T235554, start_date=20230721T235620, end_date=20230721T235627
[2023-07-21 23:56:29,566] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-07-21 23:56:29,689] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 5703. PIDs of all processes in the group: [5703]
[2023-07-21 23:56:29,841] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 5703
[2023-07-21 23:56:29,920] {process_utils.py:75} INFO - Process psutil.Process(pid=5703, status='terminated', exitcode=0, started='23:56:19') (5703) terminated with exit code 0
